[2025-03-27T16:15:09.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T16:15:09.925+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_pipelines.train_some scheduled__2025-03-27T16:10:00+00:00 [queued]>
[2025-03-27T16:15:09.936+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_pipelines.train_some scheduled__2025-03-27T16:10:00+00:00 [queued]>
[2025-03-27T16:15:09.937+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T16:15:09.950+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_some> on 2025-03-27 16:10:00+00:00
[2025-03-27T16:15:09.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T16:15:09.962+0000] {standard_task_runner.py:72} INFO - Started process 225 to run task
[2025-03-27T16:15:09.963+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_pipelines', 'train_some', 'scheduled__2025-03-27T16:10:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/***_1.py', '--cfg-path', '/tmp/tmpke7as8b5']
[2025-03-27T16:15:09.964+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask train_some
[2025-03-27T16:15:10.009+0000] {task_command.py:467} INFO - Running <TaskInstance: train_pipelines.train_some scheduled__2025-03-27T16:10:00+00:00 [running]> on host cc9d85ccd39f
[2025-03-27T16:15:10.078+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_pipelines' AIRFLOW_CTX_TASK_ID='train_some' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T16:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T16:10:00+00:00'
[2025-03-27T16:15:10.079+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T16:15:10.080+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T16:15:10.080+0000] {logging_mixin.py:190} INFO - Current task name:train_some state:running start_date:2025-03-27 16:15:09.926592+00:00
[2025-03-27T16:15:10.081+0000] {logging_mixin.py:190} INFO - Dag name:train_pipelines and current dag run status:running
[2025-03-27T16:15:10.081+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T16:15:10.083+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 82, in train
    df = pd.read_csv("./df_clear.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './df_clear.csv'
[2025-03-27T16:15:10.093+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T16:15:10.094+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 16:15:09.926592+00:00 end:2025-03-27 16:15:10.093397+00:00 duration:0.166805
[2025-03-27T16:15:10.095+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_some> dag:<DAG: train_pipelines> dagrun:<DagRun train_pipelines @ 2025-03-27 16:10:00+00:00: scheduled__2025-03-27T16:10:00+00:00, state:running, queued_at: 2025-03-27 16:15:00.484768+00:00. externally triggered: False>
[2025-03-27T16:15:10.095+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: './df_clear.csv'
[2025-03-27T16:15:10.096+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=train_pipelines, task_id=train_some, run_id=scheduled__2025-03-27T16:10:00+00:00, execution_date=20250327T161000, start_date=20250327T161509, end_date=20250327T161510
[2025-03-27T16:15:10.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T16:15:10.119+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task train_some ([Errno 2] No such file or directory: './df_clear.csv'; 225)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 82, in train
    df = pd.read_csv("./df_clear.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './df_clear.csv'
[2025-03-27T16:15:10.145+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T16:15:10.161+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T16:15:10.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
